# class exception with

## CLASS
: class 키워드를 사용하여 __자신만의 데이터타입 을 만들 수 있음.__
: class의 모든 함수는 self를 첫번째 인자로 반드시 코딩해야하는데, 이는 자바에서의 this 와 비슷함.
: 메소ㅓ드 맴버변수 모두가 기본적으로 public으로 선언되기 때문에 외부에 선언된 인스턴스를 통해 접근하여 사용이 가능하다.
### how ta make class in python?

* class 클래스이름:
    def __init__(self,parameter, ...):  # 생성자: 실행시 자동으로 한번 호출되는 함수.
    def 함수이름(self,parameter, ...)   #메서드

    + Ex 1)
    ```
    class Person:
        def __init__(self, name):       # 파이썬의 클래스가 꼭 갖는 함수. 딱히 초기로 선언할 것이 없으면 없어도 됨.
            self.name=name              # self.name => class 내의 맴버 변수. 즉 맴버 변수를 따로 선언 안해도 이렇게 바로 선언이 가능함.
            print(self.name)

        def work(self, company):
            print(self.name+company)

        def sleep(self):
            print(self.name+" sleep")
        
    obj=Person("park")
    
    obj.work("abocado")           # 
    obj.sleep()

    print("current person is", obj.name)#※obj.name은 class 내부의 맴버변수인데 외부에서 사용이 가능하다. 이는 파이썬에서 함수와 인스턴스(속성)이 모두 public이기 때문.
    ```
* class variable(변수), class method
: class variable 는 해당 클래스에서 생성된 모든 인스턴스가 공통으로 사용하는 변수. **클래스 변수는 클래스 내외부에서 "클래스명.클래스 변수명"** 으로 접근 가능. 
: class method 는 " @classmethod " 를 반드시 메서드 앞에 표시하여 해당 메서드(def)가 클래스의 method임을 표시함.
  class method 는 객체 인스턴스를 의미하는 self 대신 cls라는 클래스를 의미하는 파라미터를 인수로 전달받는다.

    + Ex 2)
    ```
    class Person:
        count=0     # class variable
        def __init__(self, name):       
            self.name=name
            Person.count+=1     # 맴버변수 count는 person class가 호출될 때마다 1씩 증가한다.    
            print(self.name)

        def work(self, company):
            print(self.name+company)

        def sleep(self):
            print(self.name+" sleep")
        
        @classmethod        # 아래 method는 class method임을 표시. 이렇게 선언된 함수는 Person.getcount() 로서 호출이 가능해진다.
        def getcount(cls):  # 예를 들어 Person.work()는 실행이 안 된다. 위 함수들은 반드시 객체화(인스턴스?)해야 호출가능해진다.
            return cls.count

    # person instance 2개 생성.
    obj1=Person("park")
    obj2=Person("LEE")
    obj1.work("abocado") # obj1의 work를 실행           
    obj2.sleep()         # obj2의 sleep 실행

    print(obj1.name,obj2.name)
    print(Person.getcount())    # 앞에 두개의 인스턴스가 두개 생성되었으므로 2가 나오고

    print(Person.count)         # person class 의 맴버변수 count 는 2이다.
    ```

### class의 모든 변수는 default로 public 상태이다. 그럼 어떻게 private로 만들까?
: private으로 만들고 싶은 맴버변수, 메소드는 이름 앞에 " __이름 " 처럼 '_' 를 두개 type한다.
: private 맴버변수, 메소드는 외부로부터 접근이 불가능하지만, class 내부에서는 서로 접근이 가능하다.(incap슐레이션)
* Ex 1)
```
class pri:
    def __init__(self,name1,name2):
        self.name1=name1
        self.__name2=name2  # private variable.
    
    def getnames(self):
        self.__printnames()             
        return self.name1,self.__name2

    def __prinnames(self):
        print(self.name1, self.__name2)

obj=pri("park","kim")

print(obj.name1)
print(obj.getnames(),type(obj.getnames()))
print(obj.__prinnames())
print(obj.__name2)

```
    -> park
    -> park kim
    -> park kim
    ->('park', 'kim' )<class 'tuple'> # 모든 def는 튜플형태로 리턴하나봄.
    -> error

### 외부에서 가져온 함수이름과 , 클래스의 메소드 이름이 같을 때 어떻게 처리할까?
: java와 다르지 않음.
* Ex)
```
def print_name(name):
    print(name)
class same:
    # init은 초기화 할 것이 없기 때문에 생략.

    def print_name(self,name):
        print("[same]"+name)
    def call_test(self):
        print_name("KIM")

        self.print_name("KIM")  # 이렇게 self를 써줌으로서 class의 내부 함수와 class 밖에 있는 같은 이름의 함수를 구별해준다.

obj= same()
print_name("LEE")
obj.print_name("LEE")
obj.call_test()
```
    -> LEE
    -> [same] LEE
    -> KIM
    -> [same] KIM

## exception ,with  : 예외처리를 해주는 exception.

#### exception 

* try: .....    except (어떤 예외인지 알려주는 해당 예외의 이름)     : try의 블록에서 에러가 발생하면 except 문으로 이동하여 예외 처리 구문을 실행.
    - ( **추가내용** ) 발생된 exception을 그냥 무시하기 위해서는 보통 pass문을 사용. 개발자가 에러를 바로 발생시키려면 raise문을 사용함.
    - ( **추가내용** ) try문은 또한 finally 문을 가질 수 있는데, finally 블럭은 try블럭과 excpet이 실행되든 항상 꼭 실행됨.

        + Ex 1)
        ```
        def calc(list_data):
            sum=0

            try:
                sum=list_data[0]+list_data[1]+list_data[2]

                if sum<0:
                    raise Exception("Sum is minus")     #raise는 인위적으로 exception을 발생시킴으로서 실제 개발도중 발생하는 다양한 에러를 파악하고 해결하기 위해 debug용으로 많이 사용한다.
            except indexError as err:
                print(str(err))
            except Exception as err:
                print(str(err))

            finally:
                print(sum)

        calc([1,2]) # try 구문에는 index[2]가 있으나 입력 데이터에는 0~1 인덱스 뿐이므로 에러가 난다.
        calc([1,2,-100]) # 인위적인 exception이 발생.
        ```
            -> list index out of range
            -> 0        # 예외에 상관없이 항상 마지막에 꼳 실행되는 finally 때문에 값이 등장.
            -> sum is minus
            -> -97      # 예외에 상관없이 항상 마지막에 꼳 실행되는 finally 때문에 값이 등장.

#### with : file, session 자동으로 resource를 close 
: 파이썬에서 with 구문을 사용시 명시적으로 리소스 close()를 안 해도 자동으로 close()를 해줌. with 블록을 벗어나는 순간 close() 한다.
: with 구문은 ML DL의 Tensorflow session 사용시 자주 사용.(그러나 session은 이제 구버전이라 안 씀.)
__일반적으로 file or session 을 사용하는 순서__ : open() => read() or write() => close

* 일반적인 방법

    + Ex)
    ```
    f= open("./file_test", 'w')
    f.write("Hello")
    f.close
    ```
* with 구문을 사용한 방법.
    + Ex)
    ```
    with open("./file_test",'w') as f:
        f.write("Hello")        # 자동으로 close()된다.
    ```